import { ReactNode } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Reporte.me',
    template: '%s | Reporte.me',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="bg-zinc-50 dark:bg-black">
      <body className={inter.className}>
        <h1 className="text-white">Root Layout</h1>
        <hr />
        {children}
      </body>
    </html>
  )
}
